language: python
matrix:
  include:
    - python: 3.5
    - python: 3.5
      before_install: pip install -q -r recommended.txt
    - python: 3.6
    - python: 3.6
      before_install: pip install -q -r recommended.txt
    - python: 3.7
    - python: 3.7
      before_install: pip install -q -r recommended.txt
install: python3 setup.py install || python setup.py install
script: python3 -m doctest morris_counter/morris_counter.py || python -m doctest morris_counter/morris_counter.py
